-- =============================================================
-- Backup do perfil antes de apagar
--
-- O usuário pode apagar o próprio perfil (currículo, skills, filtros, contatos).
-- É o direito dele, e negar isso é pior do que o risco. Mas "apagar" a pedido de
-- quem está com a sessão na mão não distingue o dono cansado de alguém que
-- entrou na conta: nos dois casos chega um DELETE autenticado, idêntico.
--
-- Então o apagar não destrói — arquiva. A linha inteira vira um retrato em JSON
-- aqui, e só o admin enxerga e restaura. Para o usuário o efeito é o mesmo (o
-- perfil some, os envios param); para um sequestro de conta, o estrago é
-- reversível enquanto a janela de retenção durar.
--
-- O que NÃO fica aqui: o arquivo do currículo em si (vive no Storage). Guardamos
-- o caminho; restaurar o perfil devolve a referência, e o arquivo continua lá
-- porque a exclusão do perfil não mexe no Storage de propósito.
-- =============================================================

create table if not exists "ProfileBackups" (
    "Id"        bigint generated by default as identity primary key,
    "UserId"    uuid not null,
    -- Retrato completo da linha de "Profiles" no momento do apagamento.
    -- jsonb e não colunas espelhadas: o perfil ganha campo novo a cada mês e um
    -- espelho desatualizado restauraria um perfil pela metade, em silêncio.
    "Snapshot"  jsonb not null,
    -- 'user' = o próprio apagou | 'admin' = apagado pelo painel
    "DeletedBy" text not null default 'user',
    -- Contexto de quem disparou, para o admin julgar se foi o dono mesmo.
    "Ip"        text,
    "UserAgent" text,
    "RestoredAt" timestamptz,
    "CreatedAt" timestamptz not null default now()
);

-- O painel lista por data (mais recentes primeiro) e busca por usuário.
create index if not exists idx_profilebackups_created on "ProfileBackups" ("CreatedAt" desc);
create index if not exists idx_profilebackups_user    on "ProfileBackups" ("UserId");
